var annotated_dup =
[
    [ "Assets", "namespace_assets.html", [
      [ "Scripts", "namespace_assets_1_1_scripts.html", [
        [ "Commands", "namespace_assets_1_1_scripts_1_1_commands.html", [
          [ "ShowCommand", "class_assets_1_1_scripts_1_1_commands_1_1_show_command.html", "class_assets_1_1_scripts_1_1_commands_1_1_show_command" ]
        ] ]
      ] ]
    ] ],
    [ "NeumorphismUI", "namespace_neumorphism_u_i.html", [
      [ "Gradient", "class_neumorphism_u_i_1_1_gradient.html", "class_neumorphism_u_i_1_1_gradient" ],
      [ "IModifier", "interface_neumorphism_u_i_1_1_i_modifier.html", "interface_neumorphism_u_i_1_1_i_modifier" ],
      [ "Neumorphism", "class_neumorphism_u_i_1_1_neumorphism.html", "class_neumorphism_u_i_1_1_neumorphism" ],
      [ "Shadow", "class_neumorphism_u_i_1_1_shadow.html", "class_neumorphism_u_i_1_1_shadow" ]
    ] ],
    [ "UnityEngine", "namespace_unity_engine.html", [
      [ "UI", "namespace_unity_engine_1_1_u_i.html", [
        [ "DropShadow", "class_unity_engine_1_1_u_i_1_1_drop_shadow.html", "class_unity_engine_1_1_u_i_1_1_drop_shadow" ]
      ] ]
    ] ],
    [ "UnityTemplateProjects", "namespace_unity_template_projects.html", [
      [ "SimpleCameraController", "class_unity_template_projects_1_1_simple_camera_controller.html", "class_unity_template_projects_1_1_simple_camera_controller" ]
    ] ],
    [ "ActionControl", "class_action_control.html", "class_action_control" ],
    [ "BodyPartVisibility", "class_body_part_visibility.html", "class_body_part_visibility" ],
    [ "BonusCollectionItem", "class_bonus_collection_item.html", "class_bonus_collection_item" ],
    [ "BonusCollections", "class_bonus_collections.html", "class_bonus_collections" ],
    [ "BoxSelection", "class_box_selection.html", "class_box_selection" ],
    [ "BrushSelection", "class_brush_selection.html", "class_brush_selection" ],
    [ "ButtonSpriteSwap", "class_button_sprite_swap.html", "class_button_sprite_swap" ],
    [ "CameraCenter", "class_camera_center.html", null ],
    [ "CameraController", "class_camera_controller.html", "class_camera_controller" ],
    [ "CameraRotationCenter", "class_camera_rotation_center.html", null ],
    [ "CollectionElement", "class_collection_element.html", "class_collection_element" ],
    [ "CollectionElementData", "class_collection_element_data.html", "class_collection_element_data" ],
    [ "Collections", "class_collections.html", "class_collections" ],
    [ "ColorPicker", "class_color_picker.html", "class_color_picker" ],
    [ "ColorPickerButton", "class_color_picker_button.html", "class_color_picker_button" ],
    [ "ContextualMenu", "class_contextual_menu.html", "class_contextual_menu" ],
    [ "CopyText", "class_copy_text.html", "class_copy_text" ],
    [ "CreateCollectionPanel", "class_create_collection_panel.html", "class_create_collection_panel" ],
    [ "CreatePrefabs", "class_create_prefabs.html", null ],
    [ "CrossPlanesGizmo", "class_cross_planes_gizmo.html", "class_cross_planes_gizmo" ],
    [ "CrossSectionPlane", "class_cross_section_plane.html", "class_cross_section_plane" ],
    [ "CrossSections", "class_cross_sections.html", "class_cross_sections" ],
    [ "CubeText", "class_cube_text.html", "class_cube_text" ],
    [ "CustomSlider", "class_custom_slider.html", "class_custom_slider" ],
    [ "CutoutMaskUI", "class_cutout_mask_u_i.html", "class_cutout_mask_u_i" ],
    [ "Cutter", "class_cutter.html", "class_cutter" ],
    [ "DeleteCommand", "class_delete_command.html", "class_delete_command" ],
    [ "DescriptionClick", "class_description_click.html", "class_description_click" ],
    [ "DownloadTranslations", "class_download_translations.html", "class_download_translations" ],
    [ "DragWindow", "class_drag_window.html", "class_drag_window" ],
    [ "DrawLineCommand", "class_draw_line_command.html", "class_draw_line_command" ],
    [ "ExpandableListItem", "class_expandable_list_item.html", "class_expandable_list_item" ],
    [ "ExpandCollapseUI", "class_expand_collapse_u_i.html", "class_expand_collapse_u_i" ],
    [ "ExpandTextUI", "class_expand_text_u_i.html", "class_expand_text_u_i" ],
    [ "Explosion", "class_explosion.html", "class_explosion" ],
    [ "ExplosionGizmo", "class_explosion_gizmo.html", "class_explosion_gizmo" ],
    [ "Fade", "class_fade.html", "class_fade" ],
    [ "FadeOut", "class_fade_out.html", "class_fade_out" ],
    [ "FirestoreAnalytics", "class_firestore_analytics.html", null ],
    [ "FPSCounter", "class_f_p_s_counter.html", "class_f_p_s_counter" ],
    [ "GizmoBehaviour", "class_gizmo_behaviour.html", "class_gizmo_behaviour" ],
    [ "GizmoDrag", "class_gizmo_drag.html", "class_gizmo_drag" ],
    [ "GlobalVariables", "class_global_variables.html", "class_global_variables" ],
    [ "HierarchyBar", "class_hierarchy_bar.html", "class_hierarchy_bar" ],
    [ "HierarchyButton", "class_hierarchy_button.html", "class_hierarchy_button" ],
    [ "HighlightText", "class_highlight_text.html", null ],
    [ "HyperlinkButton", "class_hyperlink_button.html", "class_hyperlink_button" ],
    [ "ICommand", "interface_i_command.html", "interface_i_command" ],
    [ "IncreaseHeigth", "class_increase_heigth.html", "class_increase_heigth" ],
    [ "KeyColorCommand", "class_key_color_command.html", "class_key_color_command" ],
    [ "KeyColors", "class_key_colors.html", "class_key_colors" ],
    [ "Label", "class_label.html", "class_label" ],
    [ "LabelGroup", "class_label_group.html", "class_label_group" ],
    [ "LanguageDropboxItem", "class_language_dropbox_item.html", null ],
    [ "LassoSelection", "class_lasso_selection.html", "class_lasso_selection" ],
    [ "Layers", "class_layers.html", "class_layers" ],
    [ "LayersSlider", "class_layers_slider.html", "class_layers_slider" ],
    [ "Lexicon", "class_lexicon.html", "class_lexicon" ],
    [ "LexiconElement", "class_lexicon_element.html", "class_lexicon_element" ],
    [ "LexiconElementButton", "class_lexicon_element_button.html", "class_lexicon_element_button" ],
    [ "LexiconItemCheckbox", "class_lexicon_item_checkbox.html", "class_lexicon_item_checkbox" ],
    [ "LexiconItemExpandBtn", "class_lexicon_item_expand_btn.html", "class_lexicon_item_expand_btn" ],
    [ "Line", "class_line.html", "class_line" ],
    [ "Line3D", "class_line3_d.html", "class_line3_d" ],
    [ "ListOfColliders", "class_list_of_colliders.html", "class_list_of_colliders" ],
    [ "LoadHierarchy", "class_load_hierarchy.html", "class_load_hierarchy" ],
    [ "LoadScene", "class_load_scene.html", "class_load_scene" ],
    [ "MemoryProfiler", "class_memory_profiler.html", null ],
    [ "MeshManagement", "class_mesh_management.html", "class_mesh_management" ],
    [ "MouseOverTrigger", "class_mouse_over_trigger.html", "class_mouse_over_trigger" ],
    [ "MoveCommand", "class_move_command.html", "class_move_command" ],
    [ "MoveOnDrag", "class_move_on_drag.html", "class_move_on_drag" ],
    [ "MultilanguageText", "class_multilanguage_text.html", "class_multilanguage_text" ],
    [ "MuscleGroups", "class_muscle_groups.html", "class_muscle_groups" ],
    [ "NameAndDescription", "class_name_and_description.html", "class_name_and_description" ],
    [ "NamesManagement", "class_names_management.html", "class_names_management" ],
    [ "NerveGroups", "class_nerve_groups.html", "class_nerve_groups" ],
    [ "NonDragScroll", "class_non_drag_scroll.html", "class_non_drag_scroll" ],
    [ "Note", "class_note.html", "class_note" ],
    [ "NoteGizmo", "class_note_gizmo.html", "class_note_gizmo" ],
    [ "Notes", "class_notes.html", "class_notes" ],
    [ "OpenBrowserLink", "class_open_browser_link.html", "class_open_browser_link" ],
    [ "OpenHyperlinks", "class_open_hyperlinks.html", "class_open_hyperlinks" ],
    [ "PanelProgress", "class_panel_progress.html", "class_panel_progress" ],
    [ "PanelsManagement", "class_panels_management.html", "class_panels_management" ],
    [ "Pencil", "class_pencil.html", "class_pencil" ],
    [ "PopUpManagement", "class_pop_up_management.html", "class_pop_up_management" ],
    [ "PopUpMessage", "class_pop_up_message.html", "class_pop_up_message" ],
    [ "RaycastObject", "class_raycast_object.html", "class_raycast_object" ],
    [ "ReadDB", "class_read_d_b.html", "class_read_d_b" ],
    [ "RectangleOutline", "class_rectangle_outline.html", "class_rectangle_outline" ],
    [ "RemoteConfig", "class_remote_config.html", "class_remote_config" ],
    [ "ResizeOnDrag", "class_resize_on_drag.html", "class_resize_on_drag" ],
    [ "ResizeUI", "class_resize_u_i.html", "class_resize_u_i" ],
    [ "ResolutionManager", "class_resolution_manager.html", "class_resolution_manager" ],
    [ "ResponsiveCanvas", "class_responsive_canvas.html", "class_responsive_canvas" ],
    [ "SearchEngine", "class_search_engine.html", "class_search_engine" ],
    [ "SelectCommand", "class_select_command.html", "class_select_command" ],
    [ "SelectedObjectsManagement", "class_selected_objects_management.html", "class_selected_objects_management" ],
    [ "SetBackgroundColor", "class_set_background_color.html", null ],
    [ "SetMouseSprite", "class_set_mouse_sprite.html", "class_set_mouse_sprite" ],
    [ "SetScreenSize", "class_set_screen_size.html", "class_set_screen_size" ],
    [ "SetSecondaryColor", "class_set_secondary_color.html", "class_set_secondary_color" ],
    [ "SetSurfaceColor", "class_set_surface_color.html", "class_set_surface_color" ],
    [ "SetTaskbarColor", "class_set_taskbar_color.html", null ],
    [ "Settings", "class_settings.html", "class_settings" ],
    [ "Shortcuts", "class_shortcuts.html", "class_shortcuts" ],
    [ "SliderPercentage", "class_slider_percentage.html", null ],
    [ "SplittedSlider", "class_splitted_slider.html", "class_splitted_slider" ],
    [ "SplittedSliderButton", "class_splitted_slider_button.html", "class_splitted_slider_button" ],
    [ "SwitchButton", "class_switch_button.html", "class_switch_button" ],
    [ "Tab", "class_tab.html", "class_tab" ],
    [ "TabGroup", "class_tab_group.html", "class_tab_group" ],
    [ "TangibleBodyPart", "class_tangible_body_part.html", "class_tangible_body_part" ],
    [ "ToggleChangeColor", "class_toggle_change_color.html", "class_toggle_change_color" ],
    [ "TranslateGizmo", "class_translate_gizmo.html", "class_translate_gizmo" ],
    [ "TranslateObject", "class_translate_object.html", "class_translate_object" ],
    [ "UnityAnalytics", "class_unity_analytics.html", null ],
    [ "UploadDescriptions", "class_upload_descriptions.html", "class_upload_descriptions" ],
    [ "UploadFrenchDefinitions", "class_upload_french_definitions.html", "class_upload_french_definitions" ],
    [ "VideoFromStreamingAssets", "class_video_from_streaming_assets.html", "class_video_from_streaming_assets" ],
    [ "VideoFromURL", "class_video_from_u_r_l.html", "class_video_from_u_r_l" ]
];