var hierarchy =
[
    [ "BaseMeshEffect", null, [
      [ "NeumorphismUI.Neumorphism", "class_neumorphism_u_i_1_1_neumorphism.html", null ],
      [ "UnityEngine.UI.DropShadow", "class_unity_engine_1_1_u_i_1_1_drop_shadow.html", null ]
    ] ],
    [ "Button", null, [
      [ "ButtonSpriteSwap", "class_button_sprite_swap.html", null ]
    ] ],
    [ "CollectionElementData", "class_collection_element_data.html", null ],
    [ "IBeginDragHandler", null, [
      [ "MoveOnDrag", "class_move_on_drag.html", null ]
    ] ],
    [ "ICommand", "interface_i_command.html", [
      [ "Assets.Scripts.Commands.ShowCommand", "class_assets_1_1_scripts_1_1_commands_1_1_show_command.html", null ],
      [ "DeleteCommand", "class_delete_command.html", null ],
      [ "DrawLineCommand", "class_draw_line_command.html", null ],
      [ "KeyColorCommand", "class_key_color_command.html", null ],
      [ "MoveCommand", "class_move_command.html", null ],
      [ "SelectCommand", "class_select_command.html", null ]
    ] ],
    [ "IDragHandler", null, [
      [ "CubeText", "class_cube_text.html", null ],
      [ "DragWindow", "class_drag_window.html", null ],
      [ "ExplosionGizmo", "class_explosion_gizmo.html", null ],
      [ "GizmoDrag", "class_gizmo_drag.html", null ],
      [ "MoveOnDrag", "class_move_on_drag.html", null ],
      [ "SetMouseSprite", "class_set_mouse_sprite.html", null ],
      [ "TranslateGizmo", "class_translate_gizmo.html", null ]
    ] ],
    [ "IEndDragHandler", null, [
      [ "ExplosionGizmo", "class_explosion_gizmo.html", null ],
      [ "TranslateGizmo", "class_translate_gizmo.html", null ]
    ] ],
    [ "Image", null, [
      [ "CutoutMaskUI", "class_cutout_mask_u_i.html", null ]
    ] ],
    [ "NeumorphismUI.IModifier", "interface_neumorphism_u_i_1_1_i_modifier.html", [
      [ "NeumorphismUI.Gradient", "class_neumorphism_u_i_1_1_gradient.html", null ],
      [ "NeumorphismUI.Shadow", "class_neumorphism_u_i_1_1_shadow.html", null ]
    ] ],
    [ "IPointerClickHandler", null, [
      [ "ButtonSpriteSwap", "class_button_sprite_swap.html", null ],
      [ "CubeText", "class_cube_text.html", null ],
      [ "HierarchyButton", "class_hierarchy_button.html", null ],
      [ "LexiconElementButton", "class_lexicon_element_button.html", null ],
      [ "NoteGizmo", "class_note_gizmo.html", null ],
      [ "OpenHyperlinks", "class_open_hyperlinks.html", null ],
      [ "Tab", "class_tab.html", null ]
    ] ],
    [ "IPointerDownHandler", null, [
      [ "CubeText", "class_cube_text.html", null ],
      [ "LayersSlider", "class_layers_slider.html", null ],
      [ "LexiconItemCheckbox", "class_lexicon_item_checkbox.html", null ],
      [ "LexiconItemExpandBtn", "class_lexicon_item_expand_btn.html", null ],
      [ "Line3D", "class_line3_d.html", null ],
      [ "MoveOnDrag", "class_move_on_drag.html", null ],
      [ "SetMouseSprite", "class_set_mouse_sprite.html", null ],
      [ "SplittedSliderButton", "class_splitted_slider_button.html", null ]
    ] ],
    [ "IPointerEnterHandler", null, [
      [ "CubeText", "class_cube_text.html", null ],
      [ "GizmoDrag", "class_gizmo_drag.html", null ],
      [ "LexiconElementButton", "class_lexicon_element_button.html", null ],
      [ "LexiconItemCheckbox", "class_lexicon_item_checkbox.html", null ],
      [ "LexiconItemExpandBtn", "class_lexicon_item_expand_btn.html", null ],
      [ "Line3D", "class_line3_d.html", null ],
      [ "MouseOverTrigger", "class_mouse_over_trigger.html", null ],
      [ "NoteGizmo", "class_note_gizmo.html", null ],
      [ "SetMouseSprite", "class_set_mouse_sprite.html", null ],
      [ "SplittedSliderButton", "class_splitted_slider_button.html", null ],
      [ "Tab", "class_tab.html", null ],
      [ "TranslateGizmo", "class_translate_gizmo.html", null ]
    ] ],
    [ "IPointerExitHandler", null, [
      [ "CubeText", "class_cube_text.html", null ],
      [ "GizmoDrag", "class_gizmo_drag.html", null ],
      [ "LexiconElementButton", "class_lexicon_element_button.html", null ],
      [ "Line3D", "class_line3_d.html", null ],
      [ "MouseOverTrigger", "class_mouse_over_trigger.html", null ],
      [ "NoteGizmo", "class_note_gizmo.html", null ],
      [ "SetMouseSprite", "class_set_mouse_sprite.html", null ],
      [ "Tab", "class_tab.html", null ],
      [ "TranslateGizmo", "class_translate_gizmo.html", null ]
    ] ],
    [ "IPointerUpHandler", null, [
      [ "CubeText", "class_cube_text.html", null ],
      [ "GizmoDrag", "class_gizmo_drag.html", null ],
      [ "LayersSlider", "class_layers_slider.html", null ],
      [ "MoveOnDrag", "class_move_on_drag.html", null ],
      [ "SetMouseSprite", "class_set_mouse_sprite.html", null ],
      [ "SplittedSliderButton", "class_splitted_slider_button.html", null ]
    ] ],
    [ "ReadDB.Limits", "class_read_d_b_1_1_limits.html", null ],
    [ "MonoBehaviour", null, [
      [ "ActionControl", "class_action_control.html", null ],
      [ "BodyPartVisibility", "class_body_part_visibility.html", null ],
      [ "BonusCollectionItem", "class_bonus_collection_item.html", null ],
      [ "BonusCollections", "class_bonus_collections.html", null ],
      [ "BoxSelection", "class_box_selection.html", null ],
      [ "BrushSelection", "class_brush_selection.html", null ],
      [ "CameraCenter", "class_camera_center.html", null ],
      [ "CameraController", "class_camera_controller.html", null ],
      [ "CameraRotationCenter", "class_camera_rotation_center.html", null ],
      [ "CollectionElement", "class_collection_element.html", null ],
      [ "Collections", "class_collections.html", null ],
      [ "ColorPicker", "class_color_picker.html", null ],
      [ "ColorPickerButton", "class_color_picker_button.html", null ],
      [ "ContextualMenu", "class_contextual_menu.html", null ],
      [ "CopyText", "class_copy_text.html", null ],
      [ "CreateCollectionPanel", "class_create_collection_panel.html", null ],
      [ "CreatePrefabs", "class_create_prefabs.html", null ],
      [ "CrossPlanesGizmo", "class_cross_planes_gizmo.html", null ],
      [ "CrossSectionPlane", "class_cross_section_plane.html", null ],
      [ "CrossSections", "class_cross_sections.html", null ],
      [ "CubeText", "class_cube_text.html", null ],
      [ "Cutter", "class_cutter.html", null ],
      [ "DescriptionClick", "class_description_click.html", null ],
      [ "DownloadTranslations", "class_download_translations.html", null ],
      [ "DragWindow", "class_drag_window.html", null ],
      [ "ExpandCollapseUI", "class_expand_collapse_u_i.html", null ],
      [ "ExpandTextUI", "class_expand_text_u_i.html", null ],
      [ "ExpandableListItem", "class_expandable_list_item.html", null ],
      [ "Explosion", "class_explosion.html", null ],
      [ "ExplosionGizmo", "class_explosion_gizmo.html", null ],
      [ "FPSCounter", "class_f_p_s_counter.html", null ],
      [ "Fade", "class_fade.html", null ],
      [ "FadeOut", "class_fade_out.html", null ],
      [ "FirestoreAnalytics", "class_firestore_analytics.html", null ],
      [ "GizmoBehaviour", "class_gizmo_behaviour.html", null ],
      [ "GizmoDrag", "class_gizmo_drag.html", null ],
      [ "GlobalVariables", "class_global_variables.html", null ],
      [ "HierarchyBar", "class_hierarchy_bar.html", null ],
      [ "HierarchyButton", "class_hierarchy_button.html", null ],
      [ "HighlightText", "class_highlight_text.html", null ],
      [ "HyperlinkButton", "class_hyperlink_button.html", null ],
      [ "IncreaseHeigth", "class_increase_heigth.html", null ],
      [ "KeyColors", "class_key_colors.html", null ],
      [ "Label", "class_label.html", null ],
      [ "LabelGroup", "class_label_group.html", null ],
      [ "LanguageDropboxItem", "class_language_dropbox_item.html", null ],
      [ "LassoSelection", "class_lasso_selection.html", null ],
      [ "Layers", "class_layers.html", null ],
      [ "LayersSlider", "class_layers_slider.html", null ],
      [ "Lexicon", "class_lexicon.html", null ],
      [ "LexiconElement", "class_lexicon_element.html", null ],
      [ "LexiconElementButton", "class_lexicon_element_button.html", null ],
      [ "LexiconItemCheckbox", "class_lexicon_item_checkbox.html", null ],
      [ "LexiconItemExpandBtn", "class_lexicon_item_expand_btn.html", null ],
      [ "Line", "class_line.html", null ],
      [ "Line3D", "class_line3_d.html", null ],
      [ "ListOfColliders", "class_list_of_colliders.html", null ],
      [ "LoadHierarchy", "class_load_hierarchy.html", null ],
      [ "LoadScene", "class_load_scene.html", null ],
      [ "MemoryProfiler", "class_memory_profiler.html", null ],
      [ "MeshManagement", "class_mesh_management.html", null ],
      [ "MouseOverTrigger", "class_mouse_over_trigger.html", null ],
      [ "MoveOnDrag", "class_move_on_drag.html", null ],
      [ "MultilanguageText", "class_multilanguage_text.html", null ],
      [ "MuscleGroups", "class_muscle_groups.html", null ],
      [ "NameAndDescription", "class_name_and_description.html", null ],
      [ "NamesManagement", "class_names_management.html", null ],
      [ "NerveGroups", "class_nerve_groups.html", null ],
      [ "Note", "class_note.html", null ],
      [ "NoteGizmo", "class_note_gizmo.html", null ],
      [ "Notes", "class_notes.html", null ],
      [ "OpenBrowserLink", "class_open_browser_link.html", null ],
      [ "OpenHyperlinks", "class_open_hyperlinks.html", null ],
      [ "PanelProgress", "class_panel_progress.html", null ],
      [ "PanelsManagement", "class_panels_management.html", null ],
      [ "Pencil", "class_pencil.html", null ],
      [ "PopUpManagement", "class_pop_up_management.html", null ],
      [ "PopUpMessage", "class_pop_up_message.html", null ],
      [ "RaycastObject", "class_raycast_object.html", null ],
      [ "ReadDB", "class_read_d_b.html", null ],
      [ "RectangleOutline", "class_rectangle_outline.html", null ],
      [ "RemoteConfig", "class_remote_config.html", null ],
      [ "ResizeOnDrag", "class_resize_on_drag.html", null ],
      [ "ResizeUI", "class_resize_u_i.html", null ],
      [ "ResolutionManager", "class_resolution_manager.html", null ],
      [ "ResponsiveCanvas", "class_responsive_canvas.html", null ],
      [ "SearchEngine", "class_search_engine.html", null ],
      [ "SelectedObjectsManagement", "class_selected_objects_management.html", null ],
      [ "SetBackgroundColor", "class_set_background_color.html", null ],
      [ "SetMouseSprite", "class_set_mouse_sprite.html", null ],
      [ "SetScreenSize", "class_set_screen_size.html", null ],
      [ "SetSecondaryColor", "class_set_secondary_color.html", null ],
      [ "SetSurfaceColor", "class_set_surface_color.html", null ],
      [ "SetTaskbarColor", "class_set_taskbar_color.html", null ],
      [ "Settings", "class_settings.html", null ],
      [ "Shortcuts", "class_shortcuts.html", null ],
      [ "SliderPercentage", "class_slider_percentage.html", null ],
      [ "SplittedSlider", "class_splitted_slider.html", null ],
      [ "SplittedSliderButton", "class_splitted_slider_button.html", null ],
      [ "SwitchButton", "class_switch_button.html", null ],
      [ "Tab", "class_tab.html", null ],
      [ "TabGroup", "class_tab_group.html", null ],
      [ "TangibleBodyPart", "class_tangible_body_part.html", null ],
      [ "ToggleChangeColor", "class_toggle_change_color.html", null ],
      [ "TranslateGizmo", "class_translate_gizmo.html", null ],
      [ "TranslateObject", "class_translate_object.html", null ],
      [ "UnityAnalytics", "class_unity_analytics.html", null ],
      [ "UnityTemplateProjects.SimpleCameraController", "class_unity_template_projects_1_1_simple_camera_controller.html", null ],
      [ "UploadDescriptions", "class_upload_descriptions.html", null ],
      [ "UploadFrenchDefinitions", "class_upload_french_definitions.html", null ],
      [ "VideoFromStreamingAssets", "class_video_from_streaming_assets.html", null ],
      [ "VideoFromURL", "class_video_from_u_r_l.html", null ]
    ] ],
    [ "ReadDB.pageval", "class_read_d_b_1_1pageval.html", null ],
    [ "ReadDB.Query", "class_read_d_b_1_1_query.html", null ],
    [ "ReadDB.RootObject", "class_read_d_b_1_1_root_object.html", null ],
    [ "ScrollRect", null, [
      [ "NonDragScroll", "class_non_drag_scroll.html", null ]
    ] ],
    [ "Slider", null, [
      [ "CustomSlider", "class_custom_slider.html", null ]
    ] ]
];